# Generated by Django 3.0.5 on 2022-05-24 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(choices=[('Analgesics', 'Analgesics'), ('Antacids', 'Antacids'), ('Antianxiety', 'Antianxiety'), ('Antiarrythmics', 'Antiarrythmics'), ('Antibacterials', 'Antibacterials'), ('Antibiotics', 'Antibiotics'), ('Antcoagulants and Thrombolytics', 'Antcoagulants and Thrombolytics'), ('Anticonvulsants', 'Anticonvulsants'), ('Antidepressants', 'Antidepressants'), ('Antidiarrheals', 'Antidiarrheals'), ('Antiemetics', 'Antiemetics'), ('Antifungals', 'Antifungals'), ('Antihistamins', 'Antihistamins'), ('Antihypertensives', 'Antihypertensives'), ('Anti-inflammatories', 'Anti-inflammatories'), ('Antineoplastics', 'Antineoplastics'), ('Antipsychotics', 'Antipsychotics'), ('Antipyretics', 'Antipyretics'), ('Antivirals', 'Antivirals'), ('Barbiturates', 'Barbiturates'), ('Beta-Blockers', 'Beta-Blockers'), ('Broncodilators', 'Broncodilators'), ('Cold Cures', 'Cold Cures'), ('Corticosteroids', 'Corticosteroids'), ('Cough Suppressants', 'Cough Suppressants'), ('Cytotoxics', 'Cytotoxics'), ('Decongestants', 'Decongestants'), ('Diuretics', 'Diuretics'), ('Expectorant', 'Expectorant'), ('Hormones', 'Hormones'), ('Hypoglycemics(Oral)', 'Hypoglycemics(Oral)'), ('Immunosuppresives', 'Immunosuppresives'), ('Laxatives', 'Laxatives'), ('Muscle Relaxants', 'Muscle Relaxants'), ('Sedatives', 'Sedatives'), ('Sex Hormones(Female)', 'Sex Hormones(Female)'), ('Sex Hormones(Male)', 'Sex Hormones(Male)'), ('Sleeping Drugs', 'Sleeping Drugs'), ('Tranquilizers', 'Tranquilizers'), ('Vitamins', 'Vitamins')], max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Product',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_quantity', models.PositiveIntegerField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventry.Product')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Order',
            },
        ),
    ]
